### ISSUE TITLE
Feature request: Fallback to 'traditional' method of copying when navigator.clipboard fails

### ISSUE THREAD

**Issue by Skye-31** [ghostdevv/svelte-copy#164]
On some browsers, for example DuckDuckGo on Android, `navigator.clipboard` exists, but does not function due to a Write permission error, (see https://github.com/duckduckgo/Android/issues/1695), however the fallback method works as intended.

This feature request is to attempt to use the navigator.clipboard method where possible, but if it fails, to always try the fallback method, for cases like this.

**Comment by ghostdevv** [comment]
Hey sorry for the late response, I managed to make some progress on this two weeks ago but then went away on holiday :pray:

We already have a fallback in place but that only triggers when `navigator.clipboard` doesn't exist. In cases like this where `navigator.clipboard` just doesn't work, as you found, there is just no fallback. I wanted to just automatically use the fallback but the issue with that is it *may* be a breaking change as it would make the `on:svelte-copy:error` useless as the fallback method provides no error information - although it occurs to me now that we don't document that the error event only fires when the clipboard API is used, so it might not be a big deal.

Ideas:

- A solution to it maybe being a breaking change that could be done is to add a new option that when true will automatically fallback - the downside being I don't know why you wouldn't want this on by default
- Do the opposite and make auto fallback something you can disable
- Consider this not a breaking change and automatically fallback
- Release a new major version

Interested to see what you think, and will think on it myself a little further - will try and get a patch out this/next week regardless

**Comment by Skye-31** [comment]
I think the ideal solution would be to either:
- Make it a configurable thing

Or
- Deprecate the `on:svelte-copy:error`, but don't remove it until the next major version, and automatically fallback

**Comment by Skye-31** [comment]
Closing this out as DuckduckGo now supports navigator.clipboard, and I don't require it anymore 🙂
